apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      task: worker
  template:
    metadata:
      labels:
        task: worker
    spec:
      containers:
      - name: worker
        image: qusasa-cloud-image:v4
        command: ["celery", "-A", "project_qusasa", "worker", "--loglevel=debug"]
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: qusasa-database-secrets
              key: DB_CONNECTION_STRING