# Generated by Django 4.2.6 on 2024-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0004_alter_inquiry_date_resolved"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_on", models.DateTimeField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("number_of_times", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="channelanalysishistory",
            name="analysis_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
