# Generated by Django 5.0.1 on 2024-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qusasa', '0004_alter_inquiry_date_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='inquiries/pictures/'),
        ),
    ]
