# Generated by Django 4.2.6 on 2024-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0006_remove_scheduledanalysis_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledanalysis",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("by minute", "By Minute"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=10,
            ),
        ),
    ]
