# Generated by Django 4.2.6 on 2024-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0007_alter_scheduledanalysis_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="inquiries/pictures/"
            ),
        ),
        migrations.AddField(
            model_name="playlistanalysishistory",
            name="analysis_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
