# Generated by Django 4.2.6 on 2024-05-15 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qusasa", "0005_inquiry_picture"),
        ("qusasa", "0007_alter_scheduledanalysis_frequency"),
    ]

    operations = []
